version: '3'
services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    command: mysqld --innodb_use_native_aio=0
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
    tty: true
    environment: 
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - RDS_HOST=${RDS_HOST}
      - RDS_USERNAME=${RDS_USERNAME}
      - RDS_PASSWORD=${RDS_PASSWORD}
      - RAILS_ENV=${RAILS_ENV}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  chrome:
    image: seleniarm/standalone-chromium
    ports:
      - 4444:4444
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/.nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  db-volume:
