name: Test
on: [push, workflow_dispatch]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup docker
        shell: bash
        run: |
          docker-compose build
          docker-compose up -d
        env:
          RAILS_ENV: test

      - name: sleep for waiting launch db
        run: sleep 1m

      - name: setup db
        run: docker-compose run --rm web rails db:create db:migrate

      - name: Run Rspec
        run:  |
          docker-compose run web bundle exec rspec

      - name: Run Rubocop
        run:  |
          docker-compose run web bundle exec rubocop

      - name: docker-compose down
        run: docker-compose down
