name: Test
on: [push, workflow_dispatch]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup docker
        shell: bash
        run: |
          docker-compose build
          docker-compose run web rails db:create
        env:
          RAILS_ENV: test
      - name: Run Rspec
        run:  |
          docker-compose run web bundle exec rspec
        env:
          RAILS_ENV: test
      - name: Run Rubocop
        run:  |
          docker-compose run web bundle exec rubocop
        env:
          RAILS_ENV: test